server:
  port: 9001

spring:
  application:
    name: zdw-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.169.113:8848
  rabbitmq:
    host: 110.40.169.113
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zdw_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 110.40.169.113
    password: 123456
    port: 8000
  # 邮箱
  mail:
    host: smtp.sina.com
    port: 465
    username: zengdewei317@sina.com
    password: e3bfcca627a3076b
    from: zengdewei317@sina.com
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
    default-encoding: utf-8

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

qiniu:
  oss:
    access_key: b3ulp1lDY4afMJSQswneCo67lw5Z4klBk-3Rj4WH
    secret_key: SRfDrmvBV3he-fFuLUQ0wogBemm3FPZbemlBTNOW
    bucket_name: blog-zdw
    upload_url: Http://zdwtop.cn
